### PR TITLE
Add a browserify transform to remove all checks when not in debug mode

### PR DESCRIPTION
**Pull request by mikolalysenko**
This PR adds a browserify transform which is on by default and replaces the regl requirement with an unchecked build in release mode.

This unchecked release must be built separately so we should be careful to make sure we always do that before publishing to npm.

---
This change is [Reviewable](https://reviewable.io/reviews/regl-project/regl/326)

### CODE REVIEW

**Comment by Erkaman** [comment]
"This unchecked release must be built separately", what do you mean by that? Why must it be built separately?

**Comment by mikolalysenko** [comment]
If you are building in release mode then the transform swaps out `regl.js` with `dist/regl.min.js` that removes all checks.  This saves some space in the final bundle and can slightly speed things up.

**Comment by Erkaman** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/regl-project/regl/326)*

**Comment by Erkaman** [comment]
Ok then

**Pull request merged**
