### PR TITLE
add command.destroy(), fix #481

### LINKED ISSUE #481: Destroy draw command
Related issue : #393 

Draw comand destroy is a crucial feature in many cases (including my current project). When it needs to generate commands dynamically, zoombie commands will lead to memory leaks or even crash down in the end.

So to kick off implementation, here is a launching list IMHO:

- [ ] new method: `regl({...}).destroy()` to delete generated gl program, shader, etc
- [ ] remove deleted program and shaders from local caches
- [ ] check if any cascade attribute or element buffer to destroy
  *  if a buffer is created by `regl.buffer` intentionally, NOT destroy it and leave it to user.
- [ ] test cases

Is there anything I missed? Any comment or suggestion will be highly appreciated.

### PR DESCRIPTION
**Pull request by fuzhenn**
Add a new function `destroy` to regl command, to delete webgl shaders and webgl programs.

This is useful for programs that need to create and delete webgl programs frequently.

### CODE REVIEW

**Comment by fuzhenn** [comment]
Oops, just found ref counts should be added to programCache, in case that multiple commands with the same vert or frag sources are created.

Will defend this tomorrow, please do not merge now.

**Comment by fuzhenn** [comment]
OK! 
- [x] Add ref count to REGLCommand
- [x] Test on site
- [x] Update the test case.

It's ready for review now.

**Comment by rreusser** [comment]
Thanks, @fuzhenn! This looks really good! I haven't had time to work through it yet but will try to take a look and get this merged in a reasonable timeframe.

**Comment by mikolalysenko** [comment]
Looks awesome!

**Comment by Erkaman** [comment]
6f4c132f1c192900 6f4c132f1c192900
 6f4c132f1c192900 6f4c132f1c192900

**Comment by rreusser** [comment]
Better yet. Thanks, @mikolalysenko! 🎉

**Pull request merged**
