### PR TITLE
frameSafe

### PR DESCRIPTION
**Pull request by nkint**
A convenience function `regl.frameSafe` that wraps `regl.frame` inside a `try/catch` block, plus a test and (small) documentation description.

---
This change is [Reviewable](https://reviewable.io/reviews/regl-project/regl/408)

### CODE REVIEW

**Comment by nkint** [comment]
It refers to https://github.com/regl-project/regl/issues/386

**Comment by gregtatum** [comment]
I believe in #386 and from other comments the consensus is to go ahead and replace the command. If you update the PR @nkint I will review it, otherwise I will create a new PR to do it.

**Comment by nkint** [comment]
Hi @gregtatum . Event if I'm used to git, I don't know what am I suppose to do, is the PR ok for you?
Are you going to replace my `frameSafe` with `frame` directly?
Moreover, I never heard about this *reviewable*, do I have to do something on it?
Sorry for the misunderstanding, I will try to do better on the next pr, I love regl project! : )

**Comment by gregtatum** [comment]
You should just be able to write your code like normal, and not worry about Reviewable. If you're interested and willing to work on this PR, it would be great to take your work, but instead of doing `frameSafe`, just do it in `frame` directly. I'm fine with you either rebasing your work or pushing on more commits here in place.

**Comment by nkint** [comment]
Hey, I just updated my PR, and rebased my fork to upstream.
I have exposed `frame` with `try/catch` block and `frameUnsafe` without it just in case.
Are you ok with it @gregtatum @mikolalysenko ?

**Comment by nkint** [comment]
up?

**Pull request closed without merging**
