### PR TITLE
Do not allocate a buffer to fill textures with zeroes.

### PR DESCRIPTION
**Pull request by pkenway**
## Summary
We were profiling memory use of our application, and we discovered that when we create a large texture buffer without passing in initial data for it, regl is creating a massive ArrayBuffer in the heap and holding on to it. For a 4k x 4k texture, for example, the ArrayBuffer allocated is 256 MB, since it always rounds up to the next power of 16.

Per the webGL spec here: 
https://www.khronos.org/registry/webgl/specs/latest/1.0/
```void texImage2D(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, [AllowShared] ArrayBufferView? pixels) (OpenGL ES 2.0 §3.7.1, man page) 
If pixels is null, a buffer of sufficient size initialized to 0 is passed. 
```

The change is quite simple, we allow the `data` parameter to be null when it's not passed in.

### CODE REVIEW

**Comment by pkenway** [comment]
Thank you, I will see how Firefox handles it.

**Comment by pkenway** [comment]
More info on Firefox here: https://bugzilla.mozilla.org/show_bug.cgi?id=1478216

**Comment by dy** [comment]
Yes, the main incentive was logs pollution in plotly.js.
There are some browser-specific quirks. We can disable pre-allocating buffer in the browsers that support null-data textures without warning.
We already [detect IE](https://github.com/regl-project/regl/blob/master/lib/limits.js#L95), we could do that for FF too.

**Comment by freya301** [comment]
according to this, the warning for this use case will be removed in FF65 ?
https://bugzilla.mozilla.org/show_bug.cgi?id=1478216

**Comment by dy** [comment]
I believe that was not warning but an error.

**Comment by archmoj** [comment]
@pkenway Would you mind resolving the conflicts so that we could better test it in `plotly.js`.
Thanks.

**Comment by pkenway** [comment]
@archmoj Done.

**Comment by archmoj** [comment]
> @archmoj Done.

Awesome. Thank you!

**Comment by pkenway** [comment]
@mikolalysenko Can I ask why this was closed?

**Comment by mikolalysenko** [comment]
Fixed in master now

**Pull request closed without merging**
