### PR TITLE
allow context to disable premultipliedAlpha when set to false

### PR DESCRIPTION
**Pull request by archmoj**
@rreusser

### CODE REVIEW

**Comment by rreusser** [comment]
Oh my gosh I didn't actually do that, did I? :facepalm:

**Comment by rreusser** [comment]
Sorry about that. I got in a hurry. Well, what's one more version?? I've published 1.6.1.

**Comment by archmoj** [comment]
> Oh my gosh I didn't actually do that, did I?

No. It was my dirty suggestion.

**Comment by rreusser** [comment]
Haha oh no. This is even worse. Now I've published faulty code and been passive-aggressive about it. 🙈 

(Kidding, kidding. Nbd. Published and thanks again!!)

**Comment by archmoj** [comment]
Four releases in a day. Happy regl-Day! :tada:

**Pull request merged**
