### PR TITLE
Convert to ES modules

### PR DESCRIPTION
**Pull request by Rich-Harris**
Follow-up to https://github.com/regl-project/regl/issues/118#issuecomment-252243484. Will no doubt require some finessing, but I thought I'd share what progress I've made to open it to discussion.

The headlines: `regl.min.js` is 5.8% smaller (25,093 bytes zipped, down from 26,641), and initialization time, measured like so...

```js
console.time('parse')
/* contents of regl.min.js */
console.timeEnd('parse')
```

...is reliably a decent amount faster in all the browsers I've tested (on this machine, drops from ~14ms to ~5ms on Chrome). The tests all pass and as far as I can tell all the gallery examples work as before. No changes required to the code beyond swapping `require` and `module.exports` for `import` and `export`.

As far as consumers of the library are concerned this shouldn't change anything – it's still creating a UMD bundle that behaves exactly as before. Deep imports (e.g. `require('regl/util/raf')`) wouldn't work without transpilation but I don't imagine that's a supported use case?

Let me know if you have any thoughts/questions about this approach.

---
This change is [Reviewable](https://reviewable.io/reviews/regl-project/regl/364)

### CODE REVIEW

**Comment by Rich-Harris** [comment]
Oh – a couple of things I forgot to mention. The `check-dependencies` script doesn't work with `import` declarations AFAICT, so I had to disable it. I don't know of an equivalent of `discify` for ES modules, so I disabled that too, but it was only generating a donut chart with one data point anyway.

Also, this turned into a series of slightly messy commits by the end, sorry about that – can rebase etc if nec!

Am looking into the CircleCI failure.

**Comment by mikolalysenko** [comment]
Cool! I'm ok with breaking the discify script as long as all tests pass.  It seems like this is overall a net win and I'm pretty happy with the parse time improvements.

**Comment by mikolalysenko** [comment]
Review status: 0 of 157 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[package.json, line 5 at r2](https://reviewable.io:443/reviews/regl-project/regl/364#-KTkSRBBgRyArY97W5KS:-KTkSRBCd1IYqigdLf_e:b73lz73) ([raw file](https://github.com/regl-project/regl/blob/2822670d32f8e656a7cb391e833acb713c189948/package.json#L5)):*
> ```JSON
>   "version": "1.2.1",
>   "description": "regl is a fast functional WebGL framework.",
>   "main": "dist/regl.unchecked.js",
> ```

This seems broken.  We should be exporting regl by default so that you get checks in nodejs.  We only want to remove checks in non-debug builds.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/regl-project/regl/364)*

**Comment by Rich-Harris** [comment]
Review status: 0 of 157 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[package.json, line 5 at r2](https://reviewable.io:443/reviews/regl-project/regl/364#-KTkSRBBgRyArY97W5KS:-KTkWcZ3qIVW87_uECqV:b737omh) ([raw file](https://github.com/regl-project/regl/blob/2822670d32f8e656a7cb391e833acb713c189948/package.json#L5)):*
<details><summary><i>Previously, mikolalysenko (Mikola Lysenko) wrote…</i></summary>
> This seems broken.  We should be exporting regl by default so that you get checks in nodejs.  We only want to remove checks in non-debug builds.
</details>
So it should be `dist/regl.js`? Will change. What about the `browser` field, is it necessary in that case? Not sure what the mechanism for using the debug build would be

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/regl-project/regl/364)*

**Comment by mikolalysenko** [comment]
Going through I have some general thoughs:

* This build currently removes all checks which is pretty bad.  One of the most important features of regl is that it can give sensible error messages which can also be removed in production.  Taking out error messages for all users is a serious bug and needs to be fixed before this can be merged in.
* The whole roll up process is way more complicated and messier.  It will probably slow down regl development, but since things are pretty stable right now I'm ok with this if it gives better results at the end of the day.  That said I want to make sure that we have solid integration tests so that nothing slips through in this one.
* Concatenating all scripts for checked builds is not really worth it IMO.  It also makes things harder to debug since you have to step through some inscrutable blob of code if you have an error internaly in regl.  Keeping everything in commonjs format was nicer for the non-roll up builds.  Is there maybe a way we can continue using the require syntax and also take advantage of rollup's improved build capabilities?  It doesn't seem like it would be much trouble to just do that step in a syntax transform and then avoid having to change everything.

This is a big PR, but it is probably worth it if it makes things smaller and load faster.  I like browserify much better from a development perspective, but at the end of the day the numbers here are definitely in favor of rollup.

**Comment by Rich-Harris** [comment]
Thanks for reviewing it and entertaining this idea!

> This build currently removes all checks which is pretty bad

Not sure I understand? The checks are all still there in [dist/regl.js](https://github.com/Rich-Harris/regl/blob/es-modules/dist/regl.js#L500-L503) – `regl.js` is 9490 lines while [dist/regl.unchecked.js](https://github.com/Rich-Harris/regl/blob/es-modules/dist/regl.unchecked.js) is 8211.

> The whole roll up process is way more complicated and messier. It will probably slow down regl development

What do you mean by that specifically? If there's something we can change in Rollup to improve the development workflow, let me know. Most people who have made the switch to ES modules have found that their development experience improves, because of the better static analysis etc (e.g. imports with typos are obvious compile-time errors rather than confusing runtime errors.) It just takes some getting used to 😀 

> It also makes things harder to debug since you have to step through some inscrutable blob of code if you have an error internaly in regl

I'm not sure how that's any different to a CommonJS bundle? If it's about sourcemaps, we can enable them very easily.

> Is there maybe a way we can continue using the require syntax and also take advantage of rollup's improved build capabilities?

It *does* build if you keep it as CommonJS and use a syntax transform (specifically, [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs)), but the end result is larger than the pure ES module version, so I'd recommend against it. The concepts (e.g. namespace imports) don't quite translate, and you still have to have the `require` statements even if they're just translating the statement to a module-local variable declaration. I don't quite follow why CommonJS syntax would be preferable, but if you can explain then we can try and find a solution with the best of both worlds.

🍻

**Comment by mikolalysenko** [comment]
Alright!  I think this looks great, but I do want to fix it up so we aren't using ES6 style modules where it isn't necessary and get that debug build working again.

If you're swamped with stuff I can just do it myself and then merge this in.

**Comment by Rich-Harris** [comment]
Hey – no worries, I have some changes locally which reinstate sourcemaps and the rest of the previous debug behaviour (as far as I can tell). Will push up in a sec.

> so we aren't using ES6 style modules where it isn't necessary

Can you elaborate on that? The original motivation for this in #118 was to reduce the size – that's possible because of ES6 modules. Moving the codebase back to CommonJS would undo those benefits and the parse time improvements. If it's about workflow then let me know what your concerns are, there might be something we can do

**Comment by mikolalysenko** [comment]
My thinking is to just use a babel transform to automatically convert the CommonJS modules to ES6.  This doesn't have to be perfect, just good enough to work with the regl code base.  That way we don't have to modify any existing code and still get all the benefits of using rollup's improved bundling.

**Comment by Rich-Harris** [comment]
> automatically convert the CommonJS modules to ES6

Unfortunately that's not really a thing – [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs) is probably as good a CommonJS -> ES6 converter as you'll find, and the resulting bundle is larger. (I know this because that's what I used so that I could port one module at a time and verify that I wasn't causing any tests to fail, and I watched the filesize drop as I converted each module.) I'm not sure what impact it would have on parse time – it would probably still be quicker than the current build, but not by as much.

I'm still not clear on the goal – what specifically would be the reason for keeping CommonJS modules?

**Comment by mikolalysenko** [comment]
I bet we could do something more specific for regl.  Looking at how the conversion proceeded this could even be as dumb as a regular expression.  We don't need a general purpose solution for this, just one that works for regl.

**Pull request merged**
