### PR TITLE
Simplify flattening logic

### LINKED ISSUE #248: Simplify flattening logic
Right now array-like arguments for textures are pretty complicated.  Same deal with buffers.  After chatting with @Erkaman on gitter, we came up with an interesting alternative which is to just flatten all input data eagerly and try to infer a shape from that.  If the user specified some alternative shape then override this assumption.

### PR DESCRIPTION
**Pull request by mikolalysenko**
This simplifies flattening logic for buffers and elements.  Now you can pass an arbitrarily deeply nested array into the buffer constructor and it should just work (tm).  This is nice when you are constructing a buffer from some arbitrary data source and avoids the hassle of concatenating arrays.

Fixes #248

---
This change is [Reviewable](https://reviewable.io/reviews/regl-project/regl/311)

### CODE REVIEW

**Comment by Erkaman** [comment]
*[lib/texture.js, line 784 \[r2\]](https://reviewable.io:443/reviews/regl-project/regl/311#-KR4hE9d5uiQAGv_mZym:-KR4hE9d5uiQAGv_mZyn:b97e2mu) ([raw file](https://github.com/regl-project/regl/blob/bc72cdc232d0f6265b6484215a65b1345a20d8a5/lib/texture.js#L784)):*
> ```JavaScript
>         c = c || 1
>       }
>       var arrayShape = flattenUtils.shape(data)
> ```

but is the above if-else statement really necessary? You can do it in one line I think.  Because wouldn't just c be `arrayShape[2]`, or something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/regl-project/regl/311)*

**Comment by Erkaman** [comment]
Reviewed 4 of 4 files at r1.
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/texture.js, line 1277 \[r2\]](https://reviewable.io:443/reviews/regl-project/regl/311#-KR4jIoaHh_ssa78cisS:-KR4jIobr9iT0Ikjb_mN:b-pz0hkx) ([raw file](https://github.com/regl-project/regl/blob/bc72cdc232d0f6265b6484215a65b1345a20d8a5/lib/texture.js#L1277)):*
> ```JavaScript
>       parseImage(imageData, image)
>       imageData.width = imageData.width || ((texture.width >> level) - x)
>       imageData.height = imageData.height || ((texture.height >> level) - x)
> ```

Err, shouldn't that 'x' be a 'y' here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/regl-project/regl/311)*

**Comment by mikolalysenko** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/texture.js, line 784 \[r2\]](https://reviewable.io:443/reviews/regl-project/regl/311#-KR4hE9d5uiQAGv_mZym:-KR4zZ1BueK4EtiS-WeQ:b687r0f) ([raw file](https://github.com/regl-project/regl/blob/bc72cdc232d0f6265b6484215a65b1345a20d8a5/lib/texture.js#L784)):*
<details><summary><i>Previously, Erkaman (Eric Arnebäck) wrote…</i></summary>
> but is the above if-else statement really necessary? You can do it in one line I think.  Because wouldn't just c be `arrayShape[2]`, or something?
</details>
arrayShape might be 2D though.   This could be done using a ternary operator I guess, but doesn't matter much.

---

*[lib/texture.js, line 1277 \[r2\]](https://reviewable.io:443/reviews/regl-project/regl/311#-KR4jIoaHh_ssa78cisS:-KR4zTNRxyR_yZiT5g8u:b-kl8g4c) ([raw file](https://github.com/regl-project/regl/blob/bc72cdc232d0f6265b6484215a65b1345a20d8a5/lib/texture.js#L1277)):*
<details><summary><i>Previously, Erkaman (Eric Arnebäck) wrote…</i></summary>
> Err, shouldn't that 'x' be a 'y' here?
</details>
good catch!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/regl-project/regl/311)*

**Comment by mikolalysenko** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[lib/texture.js, line 784 \[r2\]](https://reviewable.io:443/reviews/regl-project/regl/311#-KR4hE9d5uiQAGv_mZym:-KREhz2crUYPpHdqvX43:b-896fix) ([raw file](https://github.com/regl-project/regl/blob/bc72cdc232d0f6265b6484215a65b1345a20d8a5/lib/texture.js#L784)):*
<details><summary><i>Previously, mikolalysenko (Mikola Lysenko) wrote…</i></summary>
> arrayShape might be 2D though.   This could be done using a ternary operator I guess, but doesn't matter much.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/regl-project/regl/311)*

**Comment by Erkaman** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/regl-project/regl/311)*

**Comment by Erkaman** [comment]
LGTM

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/regl-project/regl/311#-:-KREiUGd5J6k6IkIda3o:bb6ywmx)*

**Pull request merged**
